### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by wtrocki** [ankitjena/coffee-maker#2]
Can we create `yargs` client that will allow us to brew coffe?

I would expect it work this way:

```
ts-coffe addrecipe --name='myfav' --milk='40' --water='60'
ts-coffe brew myfav
```

When launching brew without arguments it should be asking user for options
```
ts-coffe brew
What coffee do you want?
🔵  Mocha
⚪️ Latte
⚪️ Americano
```

EDIT: 
More options like `refillWater`. `refillMilk`, `clean` etc. possible. but classic stuff above.

**Comment by wtrocki** [comment]
ping @ankitjena

**Comment by ankitjena** [comment]
@wtrocki How to we plan to save the recipes on addrecipe? append it into a file?

**Comment by wtrocki** [comment]
It is up to you. Take look for example into yargs documentation that has this information:

https://github.com/yargs/yargs/blob/master/docs/advanced.md#building-configurable-cli-apps
